<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20251225072808 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE category (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, title VARCHAR(255) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE inventory (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, title VARCHAR(255) NOT NULL, description TEXT DEFAULT NULL, category VARCHAR(255) NOT NULL, is_public BOOLEAN NOT NULL, image_url VARCHAR(255) DEFAULT NULL, owner_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_B12D4A367E3C61F9 ON inventory (owner_id)');
        $this->addSql('CREATE TABLE inventory_user (inventory_id INT NOT NULL, user_id INT NOT NULL, PRIMARY KEY (inventory_id, user_id))');
        $this->addSql('CREATE INDEX IDX_C73519679EEA759 ON inventory_user (inventory_id)');
        $this->addSql('CREATE INDEX IDX_C7351967A76ED395 ON inventory_user (user_id)');
        $this->addSql('CREATE TABLE item (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, custom_id VARCHAR(255) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, created_by VARCHAR(255) NOT NULL, inventory_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_1F1B251E9EEA759 ON item (inventory_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_INVENTORY_CUSTOM_ID ON item (inventory_id, custom_id)');
        $this->addSql('CREATE TABLE item_field (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, title VARCHAR(255) NOT NULL, description TEXT DEFAULT NULL, is_displayed BOOLEAN NOT NULL, type VARCHAR(255) NOT NULL, order_index SMALLINT NOT NULL, inventory_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_71525E889EEA759 ON item_field (inventory_id)');
        $this->addSql('CREATE TABLE item_field_value (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, value_text TEXT DEFAULT NULL, value_number NUMERIC(2, 0) DEFAULT NULL, value_boolean BOOLEAN DEFAULT NULL, value_link TEXT DEFAULT NULL, item_id INT NOT NULL, item_field_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_D6B896F9126F525E ON item_field_value (item_id)');
        $this->addSql('CREATE INDEX IDX_D6B896F9283ACF7B ON item_field_value (item_field_id)');
        $this->addSql('CREATE TABLE tag (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE tag_inventory (tag_id INT NOT NULL, inventory_id INT NOT NULL, PRIMARY KEY (tag_id, inventory_id))');
        $this->addSql('CREATE INDEX IDX_A01A7011BAD26311 ON tag_inventory (tag_id)');
        $this->addSql('CREATE INDEX IDX_A01A70119EEA759 ON tag_inventory (inventory_id)');
        $this->addSql('CREATE TABLE "user" (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, email VARCHAR(180) NOT NULL, roles JSON NOT NULL, name VARCHAR(255) NOT NULL, password VARCHAR(255) NOT NULL, blocked BOOLEAN DEFAULT false NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_IDENTIFIER_EMAIL ON "user" (email)');
        $this->addSql('CREATE TABLE messenger_messages (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, body TEXT NOT NULL, headers TEXT NOT NULL, queue_name VARCHAR(190) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, available_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, delivered_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_75EA56E0FB7336F0 ON messenger_messages (queue_name)');
        $this->addSql('CREATE INDEX IDX_75EA56E0E3BD61CE ON messenger_messages (available_at)');
        $this->addSql('CREATE INDEX IDX_75EA56E016BA31DB ON messenger_messages (delivered_at)');
        $this->addSql('ALTER TABLE inventory ADD CONSTRAINT FK_B12D4A367E3C61F9 FOREIGN KEY (owner_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE inventory_user ADD CONSTRAINT FK_C73519679EEA759 FOREIGN KEY (inventory_id) REFERENCES inventory (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE inventory_user ADD CONSTRAINT FK_C7351967A76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE item ADD CONSTRAINT FK_1F1B251E9EEA759 FOREIGN KEY (inventory_id) REFERENCES inventory (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE item_field ADD CONSTRAINT FK_71525E889EEA759 FOREIGN KEY (inventory_id) REFERENCES inventory (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE item_field_value ADD CONSTRAINT FK_D6B896F9126F525E FOREIGN KEY (item_id) REFERENCES item (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE item_field_value ADD CONSTRAINT FK_D6B896F9283ACF7B FOREIGN KEY (item_field_id) REFERENCES item_field (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE tag_inventory ADD CONSTRAINT FK_A01A7011BAD26311 FOREIGN KEY (tag_id) REFERENCES tag (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE tag_inventory ADD CONSTRAINT FK_A01A70119EEA759 FOREIGN KEY (inventory_id) REFERENCES inventory (id) ON DELETE CASCADE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE inventory DROP CONSTRAINT FK_B12D4A367E3C61F9');
        $this->addSql('ALTER TABLE inventory_user DROP CONSTRAINT FK_C73519679EEA759');
        $this->addSql('ALTER TABLE inventory_user DROP CONSTRAINT FK_C7351967A76ED395');
        $this->addSql('ALTER TABLE item DROP CONSTRAINT FK_1F1B251E9EEA759');
        $this->addSql('ALTER TABLE item_field DROP CONSTRAINT FK_71525E889EEA759');
        $this->addSql('ALTER TABLE item_field_value DROP CONSTRAINT FK_D6B896F9126F525E');
        $this->addSql('ALTER TABLE item_field_value DROP CONSTRAINT FK_D6B896F9283ACF7B');
        $this->addSql('ALTER TABLE tag_inventory DROP CONSTRAINT FK_A01A7011BAD26311');
        $this->addSql('ALTER TABLE tag_inventory DROP CONSTRAINT FK_A01A70119EEA759');
        $this->addSql('DROP TABLE category');
        $this->addSql('DROP TABLE inventory');
        $this->addSql('DROP TABLE inventory_user');
        $this->addSql('DROP TABLE item');
        $this->addSql('DROP TABLE item_field');
        $this->addSql('DROP TABLE item_field_value');
        $this->addSql('DROP TABLE tag');
        $this->addSql('DROP TABLE tag_inventory');
        $this->addSql('DROP TABLE "user"');
        $this->addSql('DROP TABLE messenger_messages');
    }
}
