<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20251229145618 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE item_field_value DROP CONSTRAINT fk_d6b896f9283acf7b');
        $this->addSql('ALTER TABLE item_field_value DROP CONSTRAINT fk_d6b896f9126f525e');
        $this->addSql('DROP TABLE item_field_value');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE item_field_value (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, value_text TEXT DEFAULT NULL, value_number NUMERIC(2, 0) DEFAULT NULL, value_boolean BOOLEAN DEFAULT NULL, value_link TEXT DEFAULT NULL, item_id INT NOT NULL, item_field_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_d6b896f9126f525e ON item_field_value (item_id)');
        $this->addSql('CREATE INDEX idx_d6b896f9283acf7b ON item_field_value (item_field_id)');
        $this->addSql('ALTER TABLE item_field_value ADD CONSTRAINT fk_d6b896f9283acf7b FOREIGN KEY (item_field_id) REFERENCES item_field (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE item_field_value ADD CONSTRAINT fk_d6b896f9126f525e FOREIGN KEY (item_id) REFERENCES item (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
    }
}
