<?php

namespace App\Enum;

enum InventoryAttributes: string
{
    case EDIT = 'INVENTORY_EDIT';
    case DELETE = 'INVENTORY_DELETE';
    case MANAGE_ACCESS = 'INVENTORY_MANAGE_ACCESS';

    case TAB_ITEMS = 'INVENTORY_TAB_ITEMS';
    case TAB_DISCUSSION = 'INVENTORY_TAB_DISCUSSION';
    case TAB_SETTINGS = 'INVENTORY_TAB_SETTINGS';
    case TAB_CUSTOM_NUMBERS = 'INVENTORY_TAB_CUSTOM_NUMBERS';
    case TAB_ACCESS = 'INVENTORY_TAB_ACCESS';
    case TAB_STATISTICS = 'INVENTORY_TAB_STATISTICS';
}
